name: LoginMessage
main: com.tahkeh.loginmessage.LoginMessage
version: 0.8.2
authors: [Tahkeh, xZise]

commands:
    lmsg:
        aliases: [loginmessage, loginmsg, lmessage]

permissions:
    loginmessage.*:
        description: Gives permission for all LoginMessage permissions.
        default: op
        children:
            loginmessage.reload: true
    loginmessage.reload:
        description: Gives permission to reload LoginMessage files.
        default: op
