name: LoginMessage
main: com.tahkeh.loginmessage.Main
version: 0.8.1 b1
authors: [Tahkeh, xZise]

commands:
    lmsg:
        aliases: [loginmessage, loginmsg, lmessage]

permissions:
    loginmessage.*:
        description: Gives permission for all LoginMessage permissions.
        default: op
        children:
            loginmessage.reload: true
    loginmessage.reload:
        description: Gives permission to reload LoginMessage files.
        default: op
